databaseConnection:
 - port: 8001
   host: localhost
   requireAuthentication: true

piConfig:
 mode: BOARD
 ssh:
  - enable: true
    port: 22
    host: http://localhost
    username: "isus"
 
# input devices pin connections
inputDevices:
 fan: 
  - type: output
    onTime: 59043
    pin: 16
    log: true
 light:
 - type: output
   onTime: 
 
