# to get the config params for databaseConnection, use 'database'
databaseConnection:
 - port: 8001
   host: http://localhost
   requireAuthentication: false

# to get the config params for piConfig, use 'pi'
piConfig:
 - mode: BOARD
   username: isus
   password: 123456
   
# to get the config params for inputDevices, use 'input'
devices:
 fan: 
  - type: output
    automatic: true
    onTime: nil
    pin: 16
 light:
 - type: output
   automatic: true 
   onTime: nil
   pin: 23
 
