databaseConnection:
  port: 8001
  host: localhost
  requireAuthentication: false
  secret: SECRET-KEY

devices:
  - name: light
    pin: 16
    onTime: 
    every: 
    rate: 0.7
    automatic: false

  - name: coolingFan
    pins: {en: 21, in1: 20, in2: 16}
    onTime: 
    every: 
    rate: 0.7
    automatic: true
  
  - name: circulationpump
    pin: 16
    onTime: 
    every: 
    rate: 0.7
    automatic: true
  
  - name: phuppump
    pin: 16
    onTime: 
    every: 
    rate: 0.7
    automatic: true
  
  - name: phdownpump
    pin: 16
    onTime: 
    every: 
    rate: 0.7
    automatic: true
  
  - name: airpump
    pin: 16
    onTime: 
    every: 
    rate: 0.7
    automatic: true